/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerAnuncio;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelAnuncio;
import util.Formatador;

/**
 *
 * @author Ariadna Morais
 */
public class ViewAnuncio extends javax.swing.JFrame {

    ModelAnuncio modelAnuncio = new ModelAnuncio();
    ControllerAnuncio controllerAnuncio = new ControllerAnuncio();
    List<ModelAnuncio> listaModelAnuncio = new ArrayList<>();

    /**
     * Creates new form ViewAnuncio
     */
    public ViewAnuncio() {
        initComponents();
        setLocationRelativeTo(null); //Executa a tela no centro
        carregarTabela();
        somarValorTotalInvestimento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfCodAnunc = new javax.swing.JTextField();
        jtfNomeDescricao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jffDateInic = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jffDateTerm = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtAnunc = new javax.swing.JTable();
        jbSalvAnun = new javax.swing.JButton();
        jbLimpAnunc = new javax.swing.JButton();
        jbExcluAnunc = new javax.swing.JButton();
        jtfCliente = new javax.swing.JTextField();
        jtfInvPDia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfFiltro = new javax.swing.JTextField();
        jcbFiltroPesq = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jbVoltar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jbCalcularInvest = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código");

        jtfCodAnunc.setEditable(false);

        jLabel2.setText("Nome do Anúncio");

        jLabel3.setText("Cliente");

        jffDateInic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jffDateInicActionPerformed(evt);
            }
        });

        jLabel4.setText("Data de Início");

        jLabel5.setText("Data de Término");

        jLabel6.setText("Investimento por dia");

        jtAnunc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome do Anúncio", "Cliente", "Data de Início", "Data de Término", "Investimento por dia", "Qtd Máx. de Visualizações", "Qtd Máx.de Cliques", "Qtd Máx. de Compartilhamentos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtAnunc);
        if (jtAnunc.getColumnModel().getColumnCount() > 0) {
            jtAnunc.getColumnModel().getColumn(0).setMinWidth(50);
            jtAnunc.getColumnModel().getColumn(0).setPreferredWidth(50);
            jtAnunc.getColumnModel().getColumn(0).setMaxWidth(50);
            jtAnunc.getColumnModel().getColumn(2).setMinWidth(150);
            jtAnunc.getColumnModel().getColumn(2).setPreferredWidth(150);
            jtAnunc.getColumnModel().getColumn(2).setMaxWidth(150);
            jtAnunc.getColumnModel().getColumn(3).setMinWidth(120);
            jtAnunc.getColumnModel().getColumn(3).setPreferredWidth(120);
            jtAnunc.getColumnModel().getColumn(3).setMaxWidth(120);
            jtAnunc.getColumnModel().getColumn(4).setMinWidth(120);
            jtAnunc.getColumnModel().getColumn(4).setPreferredWidth(120);
            jtAnunc.getColumnModel().getColumn(4).setMaxWidth(120);
            jtAnunc.getColumnModel().getColumn(5).setMinWidth(120);
            jtAnunc.getColumnModel().getColumn(5).setPreferredWidth(120);
            jtAnunc.getColumnModel().getColumn(5).setMaxWidth(120);
            jtAnunc.getColumnModel().getColumn(6).setMinWidth(160);
            jtAnunc.getColumnModel().getColumn(6).setPreferredWidth(160);
            jtAnunc.getColumnModel().getColumn(6).setMaxWidth(160);
            jtAnunc.getColumnModel().getColumn(7).setMinWidth(150);
            jtAnunc.getColumnModel().getColumn(7).setPreferredWidth(150);
            jtAnunc.getColumnModel().getColumn(7).setMaxWidth(150);
            jtAnunc.getColumnModel().getColumn(8).setMinWidth(200);
            jtAnunc.getColumnModel().getColumn(8).setPreferredWidth(200);
            jtAnunc.getColumnModel().getColumn(8).setMaxWidth(200);
        }

        jbSalvAnun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/botoes/icons8-salvar-16.png"))); // NOI18N
        jbSalvAnun.setText("Salvar");
        jbSalvAnun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvAnunActionPerformed(evt);
            }
        });

        jbLimpAnunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/botoes/icons8-vassoura-16.png"))); // NOI18N
        jbLimpAnunc.setText("Limpar");
        jbLimpAnunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpAnuncActionPerformed(evt);
            }
        });

        jbExcluAnunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/botoes/icons8-excluir-16.png"))); // NOI18N
        jbExcluAnunc.setText("Excluir");
        jbExcluAnunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluAnuncActionPerformed(evt);
            }
        });

        jLabel7.setText("Filtro");

        jcbFiltroPesq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Período" }));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/botoes/icons8-pesquisar-16 (1).png"))); // NOI18N
        jButton6.setText("Pesquisar");

        jTextField1.setEditable(false);

        jLabel8.setText("Valor Total Investido");

        jbVoltar.setText("Voltar");
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });

        jbCalcularInvest.setText("Calcular Máximas");
        jbCalcularInvest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcularInvestActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1380, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbSalvAnun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(1232, 1232, 1232)
                                .addComponent(jSeparator1)
                                .addGap(112, 112, 112))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbLimpAnunc)
                                .addGap(18, 18, 18)
                                .addComponent(jbExcluAnunc)
                                .addGap(18, 18, 18)
                                .addComponent(jbCalcularInvest)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbVoltar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfCodAnunc, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfNomeDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfInvPDia)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jffDateInic, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jffDateTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtfFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jcbFiltroPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6)
                                .addGap(0, 23, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCodAnunc, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNomeDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfInvPDia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jffDateTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jffDateInic, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbSalvAnun, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbFiltroPesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLimpAnunc)
                    .addComponent(jbExcluAnunc)
                    .addComponent(jbVoltar)
                    .addComponent(jbCalcularInvest)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
        // TODO add your handling code here:
        new ViewPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbVoltarActionPerformed

    private void jbExcluAnuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluAnuncActionPerformed
        // TODO add your handling code here:
        int linha = jtAnunc.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um anúncio!");
        } else {
            int codigo = (int) jtAnunc.getValueAt(linha, 0);

            if (controllerAnuncio.excluirAnuncioController(codigo)) {
                carregarTabela();
                limparCampos();
                somarValorTotalInvestimento();
                JOptionPane.showMessageDialog(this, "Anúncio excluído com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir anúncio");
            }

        }
    }//GEN-LAST:event_jbExcluAnuncActionPerformed

    private void jbLimpAnuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpAnuncActionPerformed
        // TODO add your handling code here:

        limparCampos();
    }//GEN-LAST:event_jbLimpAnuncActionPerformed

    private void jbSalvAnunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvAnunActionPerformed
        // TODO add your handling code here:
        modelAnuncio = new ModelAnuncio();
        modelAnuncio.setAnuDescricao(jtfNomeDescricao.getText());
        modelAnuncio.setAnuCliente(jtfCliente.getText());
        modelAnuncio.setAnuValinvest(new Formatador().converterVirgulaParaPonto(jtfInvPDia.getText()));
        modelAnuncio.setAnuDateinicio(Double.parseDouble(jffDateInic.getText()));
        modelAnuncio.setAnuDatefim(Double.parseDouble(jffDateTerm.getText()));
        controllerAnuncio.salvarAnuncioController(modelAnuncio);
        carregarTabela();
        limparCampos();
        somarValorTotalInvestimento();
    }//GEN-LAST:event_jbSalvAnunActionPerformed

    private void jffDateInicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jffDateInicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jffDateInicActionPerformed

    //calcula os investimentos máximos
    private void jbCalcularInvestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcularInvestActionPerformed
        // TODO add your handling code here:
        
        int linha = jtAnunc.getSelectedRow();
        if (linha < 0){
            JOptionPane.showMessageDialog(this, "Selecione um anúncio!");
        }else{
            int pCondigoAnu = (int) jtAnunc.getValueAt(linha, 0);
            
            if (controllerAnuncio.calcularAnuncioController(pCondigoAnu)){
                carregarTabela();
                limparCampos();
                somarValorTotalInvestimento();
                JOptionPane.showMessageDialog(this, "Máximas calculadas com sucesso!");
            }else{
                JOptionPane.showMessageDialog(this,"Erro ao calcular máximas!");
            }
        }
    }//GEN-LAST:event_jbCalcularInvestActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, " A Função é utilizada para calcular os valores máximos de visualizações, cliques e compartilhamentos.\n"
                + "Para utilizar: Clique em um Anúncio, em seguida, clique em Calcular Máximas.");
    }//GEN-LAST:event_jButton1ActionPerformed

 
   
    /*
    * Serve para limpar os textFields
     */
    private void limparCampos() {

        jtfCodAnunc.setText("");
        jtfNomeDescricao.setText("");
        jtfCliente.setText("");
        jtfInvPDia.setText("");
        jffDateInic.setText("");
        jffDateTerm.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAnuncio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAnuncio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAnuncio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAnuncio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAnuncio().setVisible(true);
            }
        });
    }

    /*
    *Metodo serve para somar o total de investimento
     */
    private void somarValorTotalInvestimento() {
        double soma = 0;
        double valor;

        int cont = jtAnunc.getRowCount();

        for (int i = 0; i < cont; i++) {
            valor = (double) jtAnunc.getValueAt(i, 5);
            soma = soma + valor;

        }

        jTextField1.setText(String.valueOf(soma));

    }

    /**
     * Serve para recarregar a tabela de Anuncios
     */
    private void carregarTabela() {
        listaModelAnuncio = controllerAnuncio.getListaAnuncioController();
        DefaultTableModel modelo = (DefaultTableModel) jtAnunc.getModel();
        modelo.setNumRows(0);

        for (int i = 0; i < listaModelAnuncio.size(); i++) {
            modelo.addRow(new Object[]{
                listaModelAnuncio.get(i).getAnuncId(),
                listaModelAnuncio.get(i).getAnuDescricao(),
                listaModelAnuncio.get(i).getAnuCliente(),
                listaModelAnuncio.get(i).getAnuDateinicio(),
                listaModelAnuncio.get(i).getAnuDatefim(),
                listaModelAnuncio.get(i).getAnuValinvest(),
                listaModelAnuncio.get(i).getAnuQtdmaxvisu(),
                listaModelAnuncio.get(i).getAnuQtdmaxcliq(),
                listaModelAnuncio.get(i).getAnuQtdmaxcompt()
            });

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton jbCalcularInvest;
    private javax.swing.JButton jbExcluAnunc;
    private javax.swing.JButton jbLimpAnunc;
    private javax.swing.JButton jbSalvAnun;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JComboBox<String> jcbFiltroPesq;
    private javax.swing.JFormattedTextField jffDateInic;
    private javax.swing.JFormattedTextField jffDateTerm;
    private javax.swing.JTable jtAnunc;
    private javax.swing.JTextField jtfCliente;
    private javax.swing.JTextField jtfCodAnunc;
    private javax.swing.JTextField jtfFiltro;
    private javax.swing.JTextField jtfInvPDia;
    private javax.swing.JTextField jtfNomeDescricao;
    // End of variables declaration//GEN-END:variables
}